In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Suppress future warnings
import warnings
warnings.filterwarnings('ignore')

# Rest of the code remains the same as provided in the previous response


In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Step 1: Load the Iris dataset
# Assuming the dataset file 'iris.data' is in the same directory as the Jupyter Notebook
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
df = pd.read_csv('iris.data', header=None, names=column_names)

# Step 2: Separate features (X) and target variable (y)
X = df.drop('class', axis=1)  # Features (sepal_length, sepal_width, petal_length, petal_width)
y = df['class']  # Target variable (class)

# Step 3: Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 4: Feature Scaling (optional but recommended for some algorithms like KNN)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Step 5: Model Selection and Training (K-Nearest Neighbors Classifier)
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_scaled, y_train)

# Step 6: Model Evaluation
y_pred = knn.predict(X_test_scaled)

# Step 7: Calculate and print the Classification Report and Confusion Matrix
print("K-Nearest Neighbors (KNN) Classifier Accuracy:", knn.score(X_test_scaled, y_test))
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

# Step 8: Assuming you have a separate testing dataset (optional)
# df_test = pd.read_csv('iris_test.data', header=None, names=column_names)

# ... Rest of the code remains the same


K-Nearest Neighbors (KNN) Classifier Accuracy: 1.0
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30

Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [10]:
# Hyperparameter Tuning for KNN classifier
accuracy_scores = []
k_values = range(1, 21)

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)
    accuracy = knn.score(X_test_scaled, y_test)
    accuracy_scores.append(accuracy)
    print(f"k = {k}, Accuracy = {accuracy}")

# Plot the accuracy scores for different values of k
plt.figure(figsize=(8, 6))
plt.plot(k_values, accuracy_scores, marker='o', linestyle='-', color='b')
plt.xlabel('Number of Neighbors (k)')
plt.ylabel('Accuracy')
plt.title('Accuracy vs. Number of Neighbors (K) for KNN Classifier')
plt.xticks(k_values)
plt.grid(True)
plt.show()


k = 1, Accuracy = 1.0
k = 2, Accuracy = 1.0
k = 3, Accuracy = 1.0
k = 4, Accuracy = 1.0
k = 5, Accuracy = 1.0
k = 6, Accuracy = 1.0
k = 7, Accuracy = 1.0
k = 8, Accuracy = 1.0
k = 9, Accuracy = 1.0
k = 10, Accuracy = 1.0
k = 11, Accuracy = 1.0
k = 12, Accuracy = 1.0
k = 13, Accuracy = 1.0
k = 14, Accuracy = 1.0
k = 15, Accuracy = 1.0
k = 16, Accuracy = 1.0
k = 17, Accuracy = 1.0
k = 18, Accuracy = 1.0
k = 19, Accuracy = 1.0
k = 20, Accuracy = 1.0


In [12]:
from sklearn.model_selection import cross_val_score

# Create KNN classifier
knn_classifier = KNeighborsClassifier(n_neighbors=3)

# Perform cross-validation and get mean accuracy
cv_scores = cross_val_score(knn_classifier, X_train_scaled, y_train, cv=5)
mean_accuracy = cv_scores.mean()
print(f'K-Nearest Neighbors (KNN) Classifier Cross-Validation Accuracy: {mean_accuracy:.2f}')


K-Nearest Neighbors (KNN) Classifier Cross-Validation Accuracy: 0.95


In [15]:
!pip install mlxtend


     ---------------------------------------- 1.4/1.4 MB 319.4 kB/s eta 0:00:00


In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from mlxtend.plotting import plot_decision_regions

# Set the backend for matplotlib to avoid the warning
plt.switch_backend('agg')

# Load the Iris dataset
# Assuming the dataset file 'iris.data' is in the same directory as the Jupyter Notebook
column_names = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
df = pd.read_csv('iris.data', header=None, names=column_names)

# Separate features (X) and target variable (y)
X = df.drop('class', axis=1)  # Features (sepal_length, sepal_width, petal_length, petal_width)
y = df['class']  # Target variable (class)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Feature Scaling (optional but recommended for some algorithms like KNN)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Hyperparameter Tuning for KNN classifier
accuracy_scores = []
k_values = range(1, 21)

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train_scaled, y_train)
    accuracy = knn.score(X_test_scaled, y_test)
    accuracy_scores.append(accuracy)
    print(f"k = {k}, Accuracy = {accuracy}")

# Plot the accuracy scores for different values of k
plt.figure(figsize=(8, 6))
plt.plot(k_values, accuracy_scores, marker='o', linestyle='-', color='b')
plt.xlabel('Number of Neighbors (k)')
plt.ylabel('Accuracy')
plt.title('Accuracy vs. Number of Neighbors (K) for KNN Classifier')
plt.xticks(k_values)
plt.grid(True)
plt.show()

# Get the best k value based on the highest accuracy
best_k = np.argmax(accuracy_scores) + 1

# Create a KNN classifier with the best k value
knn_best = KNeighborsClassifier(n_neighbors=best_k)
knn_best.fit(X_train_scaled, y_train)

# Plot decision boundaries for KNN classifier with the best k value
plt.figure(figsize=(8, 6))
plot_decision_regions(X_train_scaled, y_train.values, clf=knn_best, legend=2)
plt.xlabel('sepal_length')
plt.ylabel('sepal_width')
plt.title(f'Decision Boundaries for KNN Classifier (k={best_k})')
plt.show()

# Model Evaluation for the best KNN classifier
y_pred = knn_best.predict(X_test_scaled)
print("K-Nearest Neighbors (KNN) Classifier Accuracy:", knn_best.score(X_test_scaled, y_test))
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))


k = 1, Accuracy = 1.0
k = 2, Accuracy = 1.0
k = 3, Accuracy = 1.0
k = 4, Accuracy = 1.0
k = 5, Accuracy = 1.0
k = 6, Accuracy = 1.0
k = 7, Accuracy = 1.0
k = 8, Accuracy = 1.0
k = 9, Accuracy = 1.0
k = 10, Accuracy = 1.0
k = 11, Accuracy = 1.0
k = 12, Accuracy = 1.0
k = 13, Accuracy = 1.0
k = 14, Accuracy = 1.0
k = 15, Accuracy = 1.0
k = 16, Accuracy = 1.0
k = 17, Accuracy = 1.0
k = 18, Accuracy = 1.0
k = 19, Accuracy = 1.0
k = 20, Accuracy = 1.0


ValueError: y must be an integer array. Found object. Try passing the array as y.astype(np.int_)

In [19]:
import matplotlib.pyplot as plt
import seaborn as sns

# Plot feature distributions
sns.pairplot(df, hue='class', palette='Set1')
plt.show()

# Plot decision boundaries for KNN classifier
from mlxtend.plotting import plot_decision_regions

plt.figure(figsize=(8, 6))
plot_decision_regions(X_train_scaled, y_train.values, clf=knn_classifier, legend=2)
plt.xlabel('sepal_length')
plt.ylabel('sepal_width')
plt.title('Decision Boundaries for K-Nearest Neighbors (KNN) Classifier')
plt.show()

ValueError: y must be an integer array. Found object. Try passing the array as y.astype(np.int_)

In [20]:
!pip install matplotlib
!pip install seaborn
!pip install mlxtend



In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from mlxtend.plotting import plot_decision_regions


In [22]:
# Assuming you have loaded your data and created the X_train_scaled, y_train, knn_classifier as before

# Plot feature distributions
sns.pairplot(df, hue='class', palette='Set1')
plt.show()

# Plot decision boundaries for KNN classifier
plt.figure(figsize=(8, 6))
plot_decision_regions(X_train_scaled, y_train, clf=knn_classifier, legend=2)
plt.xlabel('sepal_length')
plt.ylabel('sepal_width')
plt.title('Decision Boundaries for K-Nearest Neighbors (KNN) Classifier')
plt.show()


ValueError: y must be a NumPy array. Found <class 'pandas.core.series.Series'>